import type { JobListing } from "@/lib/api-client";

/** Fallback jobs when TopJobs scrape is slow or empty — always gives match scores */
export const SAMPLE_JOBS: JobListing[] = [
  {
    id: "sample-1",
    source: "sample",
    title: "Digital Marketing Executive",
    company: "Brand Lanka (Pvt) Ltd",
    location: "Colombo",
    salary_text: null,
    required_skills: ["Marketing", "SEO", "Social Media", "Content"],
    preferred_skills: ["Canva", "Google Analytics"],
    description: "Manage digital campaigns, social media, and brand content for FMCG clients.",
    apply_url: "https://www.topjobs.lk/index.jsp",
    posted_at: new Date().toISOString(),
  },
  {
    id: "sample-2",
    source: "sample",
    title: "Software Engineer",
    company: "Tech Solutions Lanka",
    location: "Colombo",
    salary_text: null,
    required_skills: ["JavaScript", "React", "SQL", "Git"],
    preferred_skills: ["TypeScript", "Node.js"],
    description: "Build web applications for enterprise clients using modern JavaScript stack.",
    apply_url: "https://www.topjobs.lk/index.jsp",
    posted_at: new Date().toISOString(),
  },
  {
    id: "sample-3",
    source: "sample",
    title: "Accounts Executive",
    company: "Finance First Ltd",
    location: "Colombo",
    salary_text: null,
    required_skills: ["Accounting", "Excel", "Finance", "SAP"],
    preferred_skills: ["Audit", "Tax"],
    description: "Handle accounts payable, receivable, and monthly financial reporting.",
    apply_url: "https://www.topjobs.lk/index.jsp",
    posted_at: new Date().toISOString(),
  },
  {
    id: "sample-4",
    source: "sample",
    title: "HR Executive",
    company: "People Plus HR",
    location: "Colombo",
    salary_text: null,
    required_skills: ["HR", "Recruitment", "Communication"],
    preferred_skills: ["Onboarding", "Payroll"],
    description: "Recruitment, employee relations, and HR administration for growing teams.",
    apply_url: "https://www.topjobs.lk/index.jsp",
    posted_at: new Date().toISOString(),
  },
  {
    id: "sample-5",
    source: "sample",
    title: "Sales Executive",
    company: "Retail Masters",
    location: "Colombo",
    salary_text: null,
    required_skills: ["Sales", "Communication", "Customer Service"],
    preferred_skills: ["B2B", "Negotiation"],
    description: "Drive sales targets and build client relationships in retail sector.",
    apply_url: "https://www.topjobs.lk/index.jsp",
    posted_at: new Date().toISOString(),
  },
  {
    id: "sample-6",
    source: "sample",
    title: "Graphic Designer",
    company: "Creative Studio SL",
    location: "Colombo",
    salary_text: null,
    required_skills: ["Design", "Photoshop", "Branding", "Creative"],
    preferred_skills: ["UI", "Illustrator"],
    description: "Create visual content for brands, social media, and marketing campaigns.",
    apply_url: "https://www.topjobs.lk/index.jsp",
    posted_at: new Date().toISOString(),
  },
];
